// Liste des thèmes pour les articles Wikipedia, organisée alphabétiquement
const List<String> articlesThemes = [
  'Agriculture',
  'Anthropologie',
  'Archéologie',
  'Architecture',
  'Art et Culture',
  'Artisanat',
  'Astronautique',
  'Astronomie',
  'Automobile',
  'Aviation',
  'Bandes dessinées',
  'Biographies',
  'Biologie',
  'Changements climatiques',
  'Chimie',
  'Cinéma',
  'Civilisations anciennes',
  'Conflits et Guerres',
  'Cosmologie',
  'Courants philosophiques',
  'Cryptographie',
  'Culture populaire',
  'Danse',
  'Dates importantes',
  'Découvertes scientifiques',
  'Démographie',
  'Design et arts graphiques',
  'Diplomatie et Relations internationales',
  'Droit',
  'Droit constitutionnel',
  'Droit international',
  'Économie',
  'Économie comportementale',
  'Écosystèmes',
  'Education',
  'Environnement',
  'Espèces animales et végétales',
  'Études de genre',
  'Événements mondiaux',
  'Exploration spatiale',
  'Faune et Flore',
  'Festivals et Célébrations',
  'Finance',
  'Folklore et contes populaires',
  'Gastronomie',
  'Géologie',
  'Géopolitique',
  'Géographie',
  'Héraldique',
  'Histoire',
  'Hydrologie',
  'Immunologie',
  'Informatique',
  'Inventions',
  'Intelligence artificielle',
  'Jeux vidéo',
  'Journalisme',
  'Kinésiologie',
  'Langues et Linguistique',
  'Législation internationale',
  'Littérature',
  'Logistique',
  'Mathématiques',
  'Médecine',
  'Météorologie',
  'Modes de vie',
  'Mouvements artistiques',
  'Mouvements sociaux',
  'Muséologie',
  'Musique',
  'Mythologie',
  'Nanotechnologie',
  'Neuroscience',
  'Numismatique',
  'Œnologie',
  'Océanographie',
  'Parapsychologie',
  'Patrimoine culturel',
  'Patrimoine mondial',
  'Pédagogie',
  'Personnages historiques',
  'Personnes célèbres',
  'Phénomènes naturels',
  'Photographie',
  'Physique',
  'Politique',
  'Pratiques médicales',
  'Psychiatrie et psychanalyse',
  'Psychologie',
  'Radio et télécommunication',
  'Religions et Croyances',
  'Réseaux sociaux',
  'Robotique',
  'Santé',
  'Science et Technologie',
  'Sciences de la Terre',
  'Sciences politiques',
  'Sécurité informatique',
  'Séries télévisées',
  'Société',
  'Spectroscopie',
  'Sport',
  'Sportif',
  'Technologie de l\'information',
  'Télécommunications',
  'Théâtre',
  'Théories scientifiques',
  'Tourisme',
  'Traditions et Coutumes',
  'Transports',
  'Urbanisme',
  'Virologie',
  'Viticulture',
  'Web design',
  'Xénobiologie',
  'Yoga',
  'Zoologie',
  'Zoothérapie',
];
